In [2]:
# importing pandas library as alias name pd
import pandas as pd
# !pip install pandas

In [3]:
# What is pandas?

# library for data analysis and manipulation
# Works with CSV, Excel, SQL,weblink etc.

In [5]:
# series in pandas
a= pd.Series([1,2,3,4,5])
print(a)
# by default stores integers as 8 bytes ie. long integers

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
# series with custom labels / index

In [7]:
c= pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
print(c)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [11]:
# DataFrames - Creation

# 👉 From dictionary

In [10]:
data = {
    'id': [101, 102, 103, 104, 105],
    'name': ['Arun', 'Nilesh', 'Ajit', 'Prashant', 'Priya'],
    'city': ['Mumbai', 'Pune', 'Surat', 'Gujarat', 'Satara']
}
df1= pd.DataFrame(data)
df1

    id      name     city
0  101      Arun   Mumbai
1  102    Nilesh     Pune
2  103      Ajit    Surat
3  104  Prashant  Gujarat
4  105     Priya   Satara

In [12]:
# From list of records to data frame

In [13]:
emp = [(101, 'HR', 'Pune'), (102, 'IT', 'Pune'), (105, 'CS', 'Pune')]
df2= pd.DataFrame(emp, columns=["id","dept","city"])
df2

    id dept  city
0  101   HR  Pune
1  102   IT  Pune
2  105   CS  Pune

In [14]:
# to convert a csv into pandas data frame

In [18]:
df3= pd.read_csv('/Superstore.csv')
df3.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2018-152156,08-11-2018,11-11-2018,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2018-152156,08-11-2018,11-11-2018,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2018-138688,12-06-2018,16-06-2018,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2017-108966,11-10-2017,18-10-2017,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2017-108966,11-10-2017,18-10-2017,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [22]:
df3.shape

(9994, 21)

In [23]:
df3.size

209874

In [24]:
# head shows first 5 columns or customized rows
df3.head(7)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2018-152156,08-11-2018,11-11-2018,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2018-152156,08-11-2018,11-11-2018,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2018-138688,12-06-2018,16-06-2018,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2017-108966,11-10-2017,18-10-2017,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2017-108966,11-10-2017,18-10-2017,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
5,6,CA-2016-115812,09-06-2016,14-06-2016,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032.0,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,7,0.00,14.1694
6,7,CA-2016-115812,09-06-2016,14-06-2016,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032.0,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.2800,4,0.00,1.9656

In [25]:
# df.sum()

# this code shows us the sum of data in each column

In [30]:
from numpy._core import numerictypes
df3.sum(numeric_only= True)  # here we will add only the numeric columns and ignore non numeric ones

Row ID         4.994502e+07
Postal Code    5.515132e+08
Sales          2.297201e+06
Quantity       3.787300e+04
Discount       1.561090e+03
Profit         2.863970e+05
dtype: float64

In [33]:
# to show mean or avg of all the numeric columns
df3.mean(numeric_only= True)

Row ID          4997.500000
Postal Code    55245.233297
Sales            229.858001
Quantity           3.789574
Discount           0.156203
Profit            28.656896
dtype: float64

In [40]:
# to check all the column names of our data set
df3.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country/Region', 'City',
       'State', 'Postal Code', 'Region', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit'],
      dtype='object')

In [43]:
# to check out a specific column
df3['Sales']

0       261.9600
1       731.9400
2        14.6200
3       957.5775
4        22.3680
          ...
9989     25.2480
9990     91.9600
9991    258.5760
9992     29.6000
9993    243.1600
Name: Sales, Length: 9994, dtype: float64

In [44]:
# to take out a column and print its total sum
df3['Sales'].sum()

np.float64(2297200.8603000003)

In [46]:
df3['Profit'].sum()

np.float64(286397.0217)

In [48]:
df3['Quantity'].sum()

np.int64(37873)

In [49]:
# df.describe()

# count: Number of non-missing values

# mean: Arithmetic average

# std: Standard deviation

# min: Minimum value

# 25%: 25th percentile (Q1)

# 50%: Median (Q2)

# 75%: 75th percentile (Q3)

# max: Maximum value

In [53]:
# converting the int columns to string that are not neccesary for numerical calculations
df3['Row ID']= df3['Row ID'].astype(str)
df3['Postal Code']= df3['Postal Code'].astype(str)

In [54]:
# df.describe()

# count: Number of non-missing values

# mean: Arithmetic average

# std: Standard deviation

# min: Minimum value

# 25%: 25th percentile (Q1)

# 50%: Median (Q2)

# 75%: 75th percentile (Q3)

# max: Maximum value

In [55]:
df3.describe()

              Sales     Quantity     Discount       Profit
count   9994.000000  9994.000000  9994.000000  9994.000000
mean     229.858001     3.789574     0.156203    28.656896
std      623.245101     2.225110     0.206452   234.260108
min        0.444000     1.000000     0.000000 -6599.978000
25%       17.280000     2.000000     0.000000     1.728750
50%       54.490000     3.000000     0.200000     8.666500
75%      209.940000     5.000000     0.200000    29.364000
max    22638.480000    14.000000     0.800000  8399.976000

In [56]:
# # df.describe(include=['object'])

# count: Number of non-missing values

# unique: Number of unique categories

# top: Most frequent category

# freq: Frequency of the most common category

In [57]:
df3.describe(include=['object'])

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name
count,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994
unique,9994,5009,1236,1334,4,793,793,3,1,531,49,631,4,1862,3,17,1850
top,9994,CA-2019-100111,05-09-2018,16-12-2017,Standard Class,WB-21850,William Brown,Consumer,United States,New York City,California,10035.0,West,OFF-PA-10001970,Office Supplies,Binders,Staple envelope
freq,1,14,38,35,5968,37,37,5191,9994,915,2001,263,3203,19,6026,1523,48

In [60]:
len(df3) # gives total no of rows

9994

In [63]:
df3.columns.size

21

In [65]:
# display records 101 to 105
df3[101:106] # 106 excluded

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
101,102,CA-2018-158568,29-08-2018,02-09-2018,Standard Class,RB-19465,Rick Bensley,Home Office,United States,Chicago,...,60610.0,Central,OFF-BI-10002609,Office Supplies,Binders,Avery Hidden Tab Dividers for Binding Systems,1.788,3,0.8,-3.0396
102,103,CA-2018-129903,01-12-2018,04-12-2018,Second Class,GZ-14470,Gary Zandusky,Consumer,United States,Rochester,...,55901.0,Central,OFF-PA-10004040,Office Supplies,Paper,Universal Premium White Copier/Laser Paper (20...,23.920,4,0.0,11.7208
103,104,US-2017-156867,13-11-2017,17-11-2017,Standard Class,LC-16870,Lena Cacioppo,Consumer,United States,Aurora,...,80013.0,West,TEC-AC-10001552,Technology,Accessories,Logitech K350 2.4Ghz Wireless Keyboard,238.896,6,0.2,-26.8758
104,105,US-2017-156867,13-11-2017,17-11-2017,Standard Class,LC-16870,Lena Cacioppo,Consumer,United States,Aurora,...,80013.0,West,FUR-FU-10004006,Furniture,Furnishings,"Deflect-o DuraMat Lighweight, Studded, Beveled...",102.360,3,0.2,-3.8385
105,106,US-2017-156867,13-11-2017,17-11-2017,Standard Class,LC-16870,Lena Cacioppo,Consumer,United States,Aurora,...,80013.0,West,OFF-BI-10002794,Office Supplies,Binders,"Avery Trapezoid Ring Binder, 3"" Capacity, Blac...",36.882,3,0.7,-25.8174

In [70]:
# for specific rows and colums
df3[['Row ID', 'Order ID', 'Sales', 'Profit', 'Region','Customer ID']][3:8]

  Row ID        Order ID     Sales    Profit Region Customer ID
3      4  US-2017-108966  957.5775 -383.0310  South    SO-20335
4      5  US-2017-108966   22.3680    2.5164  South    SO-20335
5      6  CA-2016-115812   48.8600   14.1694   West    BH-11710
6      7  CA-2016-115812    7.2800    1.9656   West    BH-11710
7      8  CA-2016-115812  907.1520   90.7152   West    BH-11710

In [71]:
# df.iloc[[n],[n]]

# this code brings the data in nth row and nth column in dataFrame

In [72]:
df3.iloc[4,5]

'SO-20335'

In [74]:
df3.iloc[89,7]

'Corporate'

In [75]:
# loc → label-based indexing (uses row/column labels, not integer positions).

In [76]:
df3.loc[45,'Category']

'Office Supplies'

In [78]:
df3.loc[69,'City']

'Springfield'

In [79]:
# to return multiple columns and rows using loc
df3.loc[3:9,['City','Category']]

              City         Category
3  Fort Lauderdale        Furniture
4  Fort Lauderdale  Office Supplies
5      Los Angeles        Furniture
6      Los Angeles  Office Supplies
7      Los Angeles       Technology
8      Los Angeles  Office Supplies
9      Los Angeles  Office Supplies

In [81]:
df3.loc[45:59:3,['Region','Sales']] # we can  use steps as well

     Region    Sales
45  Central    17.46
48     East    21.80
51  Central     6.16
54     East  1029.95
57     East   319.41

In [82]:
# df['columnName'][n]

# this code we can select and return any value of the column we want

In [83]:
df3['Segment'][5000]

'Home Office'

In [84]:
# df['ColumnName'].nunique()

# gives number of unique values in column

In [86]:
df3['State'].nunique() #total 49 states in our dataset

49

In [87]:
# df["column name"].unique()

# this code count all of the data in the column we have specified,but does not count null/none values

In [93]:
df3['Product Name'].unique()

array(['Bush Somerset Collection Bookcase',
       'Hon Deluxe Fabric Upholstered Stacking Chairs, Rounded Back',
       'Self-Adhesive Address Labels for Typewriters by Universal', ...,
       'Eureka Hand Vacuum, Bagless', 'LG G2',
       'Eldon Jumbo ProFile Portable File Boxes Graphite/Black'],
      dtype=object)

In [94]:
df3['Region'].unique()

array(['South', 'West', 'Central', 'East'], dtype=object)